"""adding page view

Revision ID: 2d11cf5992b7
Revises: 964efbc93b41
Create Date: 2020-10-07 11:10:00.123459

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2d11cf5992b7"
down_revision = "964efbc93b41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_view",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "insert_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("query", sa.String(), nullable=True),
        sa.Column("status_code", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_view_id"), "page_view", ["id"], unique=False)
    op.create_index(
        op.f("ix_page_view_insert_datetime"),
        "page_view",
        ["insert_datetime"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_view_insert_datetime"), table_name="page_view")
    op.drop_index(op.f("ix_page_view_id"), table_name="page_view")
    op.drop_table("page_view")
    # ### end Alembic commands ###
